[Unit]
After=systemd-tmpfiles-setup.service

[Service]
LogsDirectory=abservice-monitor
LogsDirectoryMode=0700
StandardOutput=append:/var/log/abservice-monitor/credentials.jsonl
StandardError=append:/var/log/abservice-monitor/credentials.jsonl
