services:
  backend:
    image: ${BACKEND_IMAGE}
    container_name: abservice-backend
    restart: unless-stopped
    environment:
      DB_URL: ${DB_URL}
      DB_REACTIVE_URL: ${DB_REACTIVE_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
