/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: {
                    catalogNumber?: string;
                    direction?: string;
                    page?: number;
                    size?: number;
                    sort?: string;
                    title?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminAlbumListResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminAlbumDetailResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/albums/{id}/preconditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preconditions */
        get: {
            parameters: {
                query?: {
                    operation?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumPreconditionsResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/article-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminArticleTagListResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: {
                    albumId?: string;
                    direction?: string;
                    page?: number;
                    publicFlag?: boolean;
                    size?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminArticleListResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminArticleDetailResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: {
                    direction?: string;
                    page?: number;
                    size?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicAlbumListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAlbumRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateAlbumResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/with-tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register With Tracks */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterAlbumWithTracksRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterAlbumWithTracksResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{albumId}/external-audios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddExternalAudioRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddExternalAudioResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{albumId}/external-audios/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderExternalAudiosRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReorderExternalAudiosResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{albumId}/external-audios/{externalAudioId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                    externalAudioId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{albumId}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddTrackRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddTrackResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{albumId}/tracks/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReorderTracksRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReorderTracksResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{albumId}/tracks/{trackId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                    trackId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTrackRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateTrackResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        /** Remove */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    albumId: string;
                    trackId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicAlbumDetailResponse"];
                    };
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        /** Update */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAlbumRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateAlbumResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteAlbumResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublishAlbumResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/albums/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unpublish */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnpublishAlbumResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: {
                    direction?: string;
                    page?: number;
                    size?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicArticleListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateArticleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateArticleResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{articleId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddArticleTagRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddArticleTagResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{articleId}/tags/{tagId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                    tagId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublicArticleDetailResponse"];
                    };
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        /** Update */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateArticleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateArticleResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{id}/album": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Album */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetArticleAlbumRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SetArticleAlbumResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        /** Remove Album */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublishArticleResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unpublish */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnpublishArticleResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Upload Url */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IssueAssetUploadUrlRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AssetUploadUrlResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{assetKey}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    assetKey: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfirmAssetUploadResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site-contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiteContentListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site-contents/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    key: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpsertSiteContentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiteContentResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tunes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List */
        get: {
            parameters: {
                query?: {
                    direction?: string;
                    page?: number;
                    size?: number;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TuneListResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTuneRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateTuneResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tunes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TuneResponse"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        /** Update */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTuneRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateTuneResponse"];
                    };
                };
                /** @description 入力の検証に失敗した */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        post?: never;
        /** Delete */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Authorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Allowed */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 対象が存在しない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetail"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddArticleTagRequest: {
            name?: string;
        };
        AddArticleTagResponse: {
            articleId: string;
            tagId: string;
            name: string;
        };
        AddExternalAudioRequest: {
            url?: string;
        };
        AddExternalAudioResponse: {
            albumId: string;
            externalAudioId: string;
            /** Format: int32 */
            displayOrder: number;
            url: string;
        };
        AddTrackRequest: {
            /** Format: int32 */
            trackNo?: number;
            title?: string;
            artistDisplayName?: string;
            artistSortKey?: string;
            tunes?: components["schemas"]["TrackTuneRequest"][];
        };
        AddTrackResponse: {
            albumId: string;
            trackId: string;
            /** Format: int32 */
            trackNo: number;
            title: string;
        };
        AdminAlbumArticleDetailResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            articleType: "ALBUM";
            articleId: string;
            title: string;
            body: string;
            bodyFormat: string;
            introShort: string;
            publishedAt: components["schemas"]["Instant"] | null;
            updatedAtBusiness: components["schemas"]["Instant"] | null;
            publicFlag: boolean;
            albumId: string | null;
            formerAlbumId: string | null;
            albumReferenceLostAt: components["schemas"]["Instant"] | null;
            albumReferenceLostReason: string | null;
            tags: components["schemas"]["AdminArticleTagResponse"][];
        };
        AdminAlbumDetailResponse: {
            albumId: string;
            title: string;
            releaseDate: string;
            artistDisplayName: string;
            artistSortKey: string | null;
            description: string | null;
            descriptionFormat: string;
            catalogNumber: string | null;
            isdn: string | null;
            eventName: string | null;
            eventDate: string | null;
            eventPlace: string | null;
            eventSpaceNumber: string | null;
            eventNote: string | null;
            publishedAt: components["schemas"]["Instant"] | null;
            coverImageKey: string | null;
            coverImageUrl: string | null;
            externalAudios: components["schemas"]["AdminExternalAudioResponse"][];
            tracks: components["schemas"]["AdminTrackResponse"][];
        };
        AdminAlbumListResponse: {
            items: components["schemas"]["AdminAlbumResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        AdminAlbumResponse: {
            albumId: string;
            title: string;
            releaseDate: string;
            artistDisplayName: string;
            catalogNumber: string | null;
            isdn: string | null;
            eventName: string | null;
            eventDate: string | null;
            eventPlace: string | null;
            eventSpaceNumber: string | null;
            eventNote: string | null;
            publishedAt: components["schemas"]["Instant"] | null;
            coverImageUrl: string | null;
        };
        AdminArticleDetailResponse: components["schemas"]["AdminAlbumArticleDetailResponse"] | components["schemas"]["AdminPlainArticleDetailResponse"];
        AdminArticleListResponse: {
            items: components["schemas"]["AdminArticleResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        AdminArticleResponse: {
            articleId: string;
            articleType: string;
            title: string;
            publishedAt: components["schemas"]["Instant"] | null;
            updatedAtBusiness: components["schemas"]["Instant"] | null;
            publicFlag: boolean;
        };
        AdminArticleTagListResponse: {
            items: components["schemas"]["AdminArticleTagResponse"][];
        };
        AdminArticleTagResponse: {
            tagId: string;
            name: string;
        };
        AdminExternalAudioResponse: {
            externalAudioId: string;
            /** Format: int32 */
            displayOrder: number;
            url: string;
        };
        AdminPlainArticleDetailResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            articleType: "NOTE" | "NEWS" | "EVENT" | "OTHER";
            articleId: string;
            title: string;
            body: string;
            bodyFormat: string;
            introShort: string;
            publishedAt: components["schemas"]["Instant"] | null;
            updatedAtBusiness: components["schemas"]["Instant"] | null;
            publicFlag: boolean;
            tags: components["schemas"]["AdminArticleTagResponse"][];
        };
        AdminTrackResponse: {
            trackId: string;
            /** Format: int32 */
            trackNo: number;
            title: string;
            artistDisplayName: string | null;
            artistSortKey: string | null;
            tunes: components["schemas"]["TrackTuneResponse"][];
        };
        AlbumDeletionPreconditionsResponse: {
            affectedArticles: components["schemas"]["PreconditionAffectedArticle"][];
        };
        AlbumPreconditionsResponse: {
            operation: string;
            deletion: components["schemas"]["AlbumDeletionPreconditionsResponse"] | null;
            unpublication: components["schemas"]["AlbumUnpublicationPreconditionsResponse"] | null;
        };
        AlbumUnpublicationPreconditionsResponse: {
            articlesBecomingUnpublished: components["schemas"]["CascadeUnpublishedArticle"][];
        };
        AssetUploadUrlResponse: {
            assetKey: string;
            uploadUrl: string;
            expiresAt: components["schemas"]["Instant"];
            /** Format: int64 */
            maxBytes: number;
        };
        CascadeUnpublishedArticle: {
            articleId: string;
            title: string;
        };
        CascadeUnpublishedArticleResponse: {
            articleId: string;
            title: string;
        };
        ConfirmAssetUploadResponse: {
            assetKey: string;
            url: string;
            contentType: string;
            /** Format: int64 */
            sizeBytes: number;
        };
        CreateAlbumRequest: {
            title?: string;
            releaseDate?: string;
            artistDisplayName?: string;
            artistSortKey?: string;
            catalogNumber?: string;
            isdn?: string;
            coverImageKey?: string;
            description?: string;
            descriptionFormat?: string;
            event?: components["schemas"]["EventRequest2"];
        };
        CreateAlbumResponse: {
            albumId: string;
            title: string;
            releaseDate: string;
            artistDisplayName: string;
        };
        CreateArticleRequest: {
            articleType?: string;
            title?: string;
            body?: string;
            bodyFormat?: string;
            introShort?: string;
        };
        CreateArticleResponse: {
            articleId: string;
            articleType: string;
            title: string;
            publicFlag: boolean;
        };
        CreateTuneRequest: {
            title?: string;
            tuneKind?: string;
            defaultComposerCredit?: string;
            defaultArrangerCredit?: string;
            originalWorkTitle?: string;
            originalWorkCredit?: string;
            tuneType?: string;
            defaultKey?: string;
            /** Format: int32 */
            defaultTempo?: number;
        };
        CreateTuneResponse: {
            tuneId: string;
            title: string;
            tuneKind: string;
        };
        DeleteAlbumResponse: {
            affectedArticles: components["schemas"]["DeletionAffectedArticle"][];
        };
        DeletionAffectedArticle: {
            articleId: string;
            title: string;
            unpublished: boolean;
        };
        EventRequest: {
            name?: string;
            date?: string;
            place?: string;
            spaceNumber?: string;
            note?: string;
        };
        EventRequest1: {
            name?: string;
            date?: string;
            place?: string;
            spaceNumber?: string;
            note?: string;
        };
        EventRequest2: {
            name?: string;
            date?: string;
            place?: string;
            spaceNumber?: string;
            note?: string;
        };
        ExternalAudioOrderEntryResponse: {
            externalAudioId: string;
            /** Format: int32 */
            displayOrder: number;
        };
        FieldError: {
            field?: string;
            message?: string;
            code?: string;
        };
        /**
         * Format: date-time
         * @example 2022-03-10T16:15:50Z
         */
        Instant: string;
        IssueAssetUploadUrlRequest: {
            contentType?: string;
        };
        PreconditionAffectedArticle: {
            articleId: string;
            title: string;
            losesAlbumReference: boolean;
            becomesUnpublished: boolean;
        };
        ProblemDetail: {
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            errors?: components["schemas"]["FieldError"][];
        };
        PublicAlbumArticleDetailResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            articleType: "ALBUM";
            articleId: string;
            title: string;
            body: string;
            bodyFormat: string;
            publishedAt: components["schemas"]["Instant"];
            albumId: string | null;
            tags: string[];
        };
        PublicAlbumArticleResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            articleType: "ALBUM";
            articleId: string;
            title: string;
            introShort: string;
            publishedAt: components["schemas"]["Instant"];
            albumId: string | null;
        };
        PublicAlbumDetailResponse: {
            albumId: string;
            title: string;
            releaseDate: string;
            artistDisplayName: string;
            description: string | null;
            descriptionFormat: string;
            catalogNumber: string | null;
            isdn: string | null;
            eventName: string | null;
            eventDate: string | null;
            eventPlace: string | null;
            eventSpaceNumber: string | null;
            eventNote: string | null;
            publishedAt: components["schemas"]["Instant"];
            coverImageUrl: string | null;
            externalAudios: components["schemas"]["PublicExternalAudioResponse"][];
            tracks: components["schemas"]["PublicTrackResponse"][];
        };
        PublicAlbumListResponse: {
            items: components["schemas"]["PublicAlbumResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PublicAlbumResponse: {
            albumId: string;
            title: string;
            releaseDate: string;
            artistDisplayName: string;
            catalogNumber: string | null;
            isdn: string | null;
            eventName: string | null;
            eventDate: string | null;
            eventPlace: string | null;
            eventSpaceNumber: string | null;
            eventNote: string | null;
            publishedAt: components["schemas"]["Instant"];
            coverImageUrl: string | null;
        };
        PublicArticleDetailResponse: components["schemas"]["PublicAlbumArticleDetailResponse"] | components["schemas"]["PublicPlainArticleDetailResponse"];
        PublicArticleListResponse: {
            items: components["schemas"]["PublicArticleResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        PublicArticleResponse: components["schemas"]["PublicAlbumArticleResponse"] | components["schemas"]["PublicPlainArticleResponse"];
        PublicExternalAudioResponse: {
            /** Format: int32 */
            displayOrder: number;
            url: string;
        };
        PublicPlainArticleDetailResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            articleType: "NOTE" | "NEWS" | "EVENT" | "OTHER";
            articleId: string;
            title: string;
            body: string;
            bodyFormat: string;
            publishedAt: components["schemas"]["Instant"];
            tags: string[];
        };
        PublicPlainArticleResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            articleType: "NOTE" | "NEWS" | "EVENT" | "OTHER";
            articleId: string;
            title: string;
            introShort: string;
            publishedAt: components["schemas"]["Instant"];
        };
        PublicTrackResponse: {
            /** Format: int32 */
            trackNo: number;
            title: string;
            artistDisplayName: string | null;
            tunes: components["schemas"]["TrackTuneResponse"][];
        };
        PublishAlbumResponse: {
            albumId: string;
            title: string;
            published: boolean;
        };
        PublishArticleResponse: {
            articleId: string;
            articleType: string;
            title: string;
            publicFlag: boolean;
        };
        RegisterAlbumWithTracksRequest: {
            title?: string;
            releaseDate?: string;
            artistDisplayName?: string;
            artistSortKey?: string;
            catalogNumber?: string;
            isdn?: string;
            coverImageKey?: string;
            description?: string;
            descriptionFormat?: string;
            event?: components["schemas"]["EventRequest1"];
            tracks?: components["schemas"]["TrackRequest"][];
        };
        RegisterAlbumWithTracksResponse: {
            albumId: string;
            title: string;
            releaseDate: string;
            artistDisplayName: string;
            tracks: components["schemas"]["TrackSummaryResponse"][];
        };
        ReorderExternalAudiosRequest: {
            orderedExternalAudioIds?: string[];
        };
        ReorderExternalAudiosResponse: {
            albumId: string;
            externalAudios: components["schemas"]["ExternalAudioOrderEntryResponse"][];
        };
        ReorderTracksRequest: {
            orderedTrackIds?: string[];
        };
        ReorderTracksResponse: {
            albumId: string;
            tracks: components["schemas"]["TrackOrderEntryResponse"][];
        };
        SetArticleAlbumRequest: {
            albumId?: string;
        };
        SetArticleAlbumResponse: {
            articleId: string;
            articleType: string;
            albumId: string;
            title: string;
        };
        SiteContentListResponse: {
            items: components["schemas"]["SiteContentResponse"][];
        };
        SiteContentResponse: {
            key: string;
            content: string;
            contentFormat: string;
        };
        TrackOrderEntryResponse: {
            trackId: string;
            /** Format: int32 */
            trackNo: number;
        };
        TrackRequest: {
            /** Format: int32 */
            trackNo?: number;
            title?: string;
            artistDisplayName?: string;
            artistSortKey?: string;
            tunes?: components["schemas"]["TrackTuneRequest"][];
        };
        TrackSummaryResponse: {
            trackId: string;
            /** Format: int32 */
            trackNo: number;
            title: string;
        };
        TrackTuneRequest: {
            /** Format: int32 */
            seq?: number;
            tuneTitle?: string;
            composerCreditOverride?: string;
            arrangerCreditOverride?: string;
            linkUrl?: string;
        };
        TrackTuneResponse: {
            /** Format: int32 */
            seq: number;
            tuneTitle: string | null;
            composerCreditOverride: string | null;
            arrangerCreditOverride: string | null;
            linkUrl: string | null;
        };
        TuneListResponse: {
            items: components["schemas"]["TuneResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        TuneResponse: {
            tuneId: string;
            title: string;
            tuneKind: string;
            defaultComposerCredit: string | null;
            defaultArrangerCredit: string | null;
            originalWorkTitle: string | null;
            originalWorkCredit: string | null;
            tuneType: string | null;
            defaultKey: string | null;
            /** Format: int32 */
            defaultTempo: number | null;
        };
        UnpublishAlbumResponse: {
            albumId: string;
            title: string;
            published: boolean;
            cascadeUnpublishedArticles: components["schemas"]["CascadeUnpublishedArticleResponse"][];
        };
        UnpublishArticleResponse: {
            articleId: string;
            articleType: string;
            title: string;
            publicFlag: boolean;
        };
        UpdateAlbumRequest: {
            title?: string;
            releaseDate?: string;
            artistDisplayName?: string;
            artistSortKey?: string;
            catalogNumber?: string;
            isdn?: string;
            coverImageKey?: string;
            description?: string;
            descriptionFormat?: string;
            event?: components["schemas"]["EventRequest"];
        };
        UpdateAlbumResponse: {
            albumId: string;
            title: string;
            releaseDate: string;
            artistDisplayName: string;
        };
        UpdateArticleRequest: {
            articleType?: string;
            title?: string;
            body?: string;
            bodyFormat?: string;
            introShort?: string;
        };
        UpdateArticleResponse: {
            articleId: string;
            articleType: string;
            title: string;
            publicFlag: boolean;
        };
        UpdateTrackRequest: {
            /** Format: int32 */
            trackNo?: number;
            title?: string;
            artistDisplayName?: string;
            artistSortKey?: string;
            tunes?: components["schemas"]["TrackTuneRequest"][];
        };
        UpdateTrackResponse: {
            albumId: string;
            trackId: string;
            /** Format: int32 */
            trackNo: number;
            title: string;
        };
        UpdateTuneRequest: {
            title?: string;
            tuneKind?: string;
            defaultComposerCredit?: string;
            defaultArrangerCredit?: string;
            originalWorkTitle?: string;
            originalWorkCredit?: string;
            tuneType?: string;
            defaultKey?: string;
            /** Format: int32 */
            defaultTempo?: number;
        };
        UpdateTuneResponse: {
            tuneId: string;
            title: string;
            tuneKind: string;
        };
        UpsertSiteContentRequest: {
            content?: string;
            contentFormat?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
